export const REQUEST_DATA = 'REQUEST_DATA';
export const GET_NEXT_ITEMS = 'GET_NEXT_ITEMS';
export const ADD_TO_FAVORITE = 'ADD_TO_FAVORITE';
export const REMOVE_FROM_FAVORITE = 'REMOVE_FROM_FAVORITE';
export const GET_EXACT_BEER = 'GET_EXACT_BEER';
export const SEARCH_BEERS = 'SEARCH_BEERS';
export const APPLY_FILTERS = 'APPLY_FILTERS';
